[package]
name = "dy-weekly-generator"
version = "0.3.6"
authors = ["codeworm96 <codeworm96@outlook.com>"]
edition = "2021"

[[bin]]
name = "weekly-gen"

[dependencies]
clap = "2.33"
reqwest = { version = "0.11", features = ["blocking"] }
json = "0.12"
yaml-rust = "0.4"
regex = "1.3"
lazy_static = "1.4"
